oneapp_mobile_url_th: "https://api.dev.customer.it-lotus.com/oneapp-mobile-bff"
oneapp_mobile_url_my: "https://api.dev.customer.my.it-lotus.com/oneapp-mobile-bff"

key: 
  type_th: "pTYOfVEEnzXZEH130zzRQEkXh8L5qFdvAzK6zJZrtyyhpTpZttesJYc4uR4t04asWiN8Tc6TvHMeSVgIKsfKVdHV76xextLvFCiTn4bDKXyLg693bVjfKirdE7QuXA5g"
  type_my: "3lxMO20ZkATy15hpfPbSarJQi8Iu7GBNHUisB5S7693Gdce0ZmbJAqEKnyvjklNrfw1OM2oRPahtpLzTFxIYu4CQDWg8VX"