oneapp_mobile_url_th: "https://api.qa.customer.it-lotus.com/oneapp-mobile-bff"
oneapp_mobile_url_my: "https://api.qa.customer.my.it-lotus.com/oneapp-mobile-bff"

key:
  type_th: "cL1wvTEJcL3d6UFdZQUk4WlR1XC84S1N"
  type_my: "8X2fGMCgclNqYL4IRBzHOs61ZmQkTu9eu5RGTw8cfAtUlXa96FqEz1mJneMgOhkHP0jNS7Ys4V3pLvibDIBodCWQyZx2Kr"