oneapp_mobile_url_th: "https://ppe-api-customer.lotuss.com/oneapp-mobile-bff"
oneapp_mobile_url_my: "https://ppe-api-customer.lotuss.com.my/oneapp-mobile-bff"

key: 
  type_th: "caj6gKrnHQ7hox9XVS-hWyLHQwnRauQt"
  type_my: "3C8xkuorJwh9liU1yFEHTdcXV4W6K7nfTFdJeqClSrMnfipAtVOzWvQsRkDIw0PGxa75LgH3Zh18cymX9KoB4NY2Eb6Uju"